# DB LOCAL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=2

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LOGS
logging.level.org.springframework.security=DEBUG

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Mercado Pago
mercadopago.access-token=${MP_ACCESS_TOKEN}
mercadopago.notification-url=http://localhost:8080/api/webhooks/mercadopago
mercadopago.back-urls.success=http://localhost:5173/payment/success
mercadopago.back-urls.failure=http://localhost:5173/payment/failure
mercadopago.back-urls.pending=http://localhost:5173/payment/pending